### ISSUE TITLE
Excellent project! A few questions...

### ISSUE THREAD

**Issue by Aiki-bot51** [knee-koh/MarIOnette#12]
First off, what an exquisite open source piece of software!
This is exactly what i have been searching for years

As for the questions, i am planning on using an i2c module. I assume you are using that for the spider robot in the demo. What modification and where to apply to use it?

I am very intrigued about the unreleased feedback-function on the puppet demo.... that is exactly the thing i was looking for. I assume that is done using a modified mg/sg90s servo using a potentiometer? Or is that just potentiometer? It would be great if you would release that feature, with support for modified servos using potentiometers!

I hope this gets more traction so people can fork and CD functions

**Comment by knee-koh** [comment]
Hi, apologies for the late reply and thanks for your interest in the project!

For the spider robot, I am using [UART bus servos](https://www.amazon.com/dp/B073WR3SK9/ref=emc_bcc_2_i?th=1) though [this module](https://www.amazon.com/LewanSoul-BusLinker-Debug-Board-LX-16A/dp/B073WRLJB2/ref=sr_1_21?crid=1FM8SM6GHL36M&dib=eyJ2IjoiMSJ9.pirMjdSUFo3BlfbWvkTbNiB9J_wgZ4yPuKbElduzx6VS8dYfJfRyTr1V2dffaTIltJ5rAKI_mFd_L22J3SQ8JNm_e-9CefH_wZb7aaZqrsXYNfpUA-h505MKgAVnZS2ATMZHV_2nIX7bCa5nHX5VvkJDAPr4WE4JrbhXfEUABQUO9ifUhVbXo9j17XD2h3Hiw1EP5VW3vY2Xr4dmgUP2eCqAfq8EWC-kYHK68YYJvY4Hy5QgQNMfgxeZWFPUdsECzZIkjWQ1aGzRgwNaJF0IA5-WEHumRJG8YgJOXqsHHP8.G6-QTL05n-Y-LaNrHT4C_w7wJ6EoEzbYjyQfOFjzmo0&dib_tag=se&keywords=lewansoul&qid=1721071939&sprefix=lewansoul%2Caps%2C140&sr=8-21). They have built-in positional feedback similar to Dynamixels, and that's what you're seeing in the "puppeteering mode" on the main page in the "Coming Soon" section. These types of servos usually communicate over a Serial port, so you'll have to choose a microcontroller with a few onboard like the Arduino Mega, ESP32, or Teensy 3.2 and up.

Modified servos are a great idea as well, once I figure out the right implementation of "puppeteering mode" I can add other inputs that MarIOnette can use to drive bones in the viewport and record animations.

**Comment by TheOnlyThing** [comment]
Did you end up finding a solution to this problem? Im facing a similar thing.
