### ISSUE TITLE
error when compiling arduino code for esp32 with servo code

### ISSUE THREAD

**Issue by hcgilje** [knee-koh/MarIOnette#17]
I get an error when exporting a setup with servos when using esp32.

/Users/hcg/Library/Arduino15/libraries/Servo/src/Servo.h:77:2: error:#error "This library only supports boards with an AVR, SAM, SAMD, NRF52 or STM32F4 processor."
Maybe it would be possible to add https://github.com/madhephaestus/ESP32Servo as the default servo library for esp32?

**Comment by knee-koh** [comment]
I've pushed a new release that should support ESP32 and servo motors (using the ESP32Servo library that comes standard with ESP32 microcontrollers in Arduino). Neopixels are also confirmed to work, but I haven't checked other actuators that rely on external libraries just yet (like Stepper Motors, Dynamixels, or other bus servos).
