### ISSUE TITLE
Unable to install add-on for Blender 4.2.3

### ISSUE THREAD

**Issue by destin-v** [knee-koh/MarIOnette#18]
I have been following the instructions for installing this add-on for Blender 4.2.3 but have been unable to do so.  I am working on Mac (Intel Based).  When installing the add-on it will show up in the list.  But any attempts to check the box to use the add-on fails.  I have not downloaded an older version of Blender to test on yet.  But having it updated to work with Blender >4.2 would be great.

**Comment by knee-koh** [comment]
Hi, Blender changed the way add-ons are handled after version 4.2.

I am currently working to resolve this, but in the meantime please follow the guide (bottom of the page) here: https://docs.blender.org/manual/en/latest/editors/preferences/addons.html

Alternatively, you can extract the python file inside the .zip, then open and run it from the Scripting tab inside Blender.

**Comment by knee-koh** [comment]
Hi @destin-v, I've updated the add-on for Blender 4.2 and later. Please download the .zip file again from the Blender Script folder on the Github. 

I've tested on Apple Silicon and Windows 11, both of which work without issues.
