### ISSUE TITLE
Missing precompiler case for LED's but no motors.

### ISSUE THREAD

**Issue by baldyman01** [knee-koh/MarIOnette#4]
In the generated arduino.ino there's no pre-compiler case for having LED's but no motors. 

You have a case for motors and LEDs, a case for motors but no LED, but not LEDs and no motors.  If you hook up just an LED, which I did to test it, it leaves servos[] undefined.

`
#if TOTAL_SERVOS > 0 && TOTAL_LEDS > 0
  PWMServo servos[TOTAL_MOTORS];
#elif TOTAL_SERVOS > 0 && TOTAL_LEDS == 0
  Servo servos[TOTAL_MOTORS];
#endif
` 

Cheers

Pete

**Comment by knee-koh** [comment]
Updated to include this change in v1_0_1.
