### ISSUE TITLE
9600 boud speed issue 

### ISSUE THREAD

**Issue by strangerest** [knee-koh/MarIOnette#5]
Hi! Maybe it is only my issue but i faced some framing errors on 9600 boud speed ( same errors on blender 3.5.0 and 3.3.1 regardless USB port) Windows OS
![image](https://user-images.githubusercontent.com/57198812/231771989-1f3b67a7-8be0-44e0-8c86-28c790169412.png)

I tried on 19200 and 34800 boud and it worked smoothly. (it is strange a little bit, because opposite effect was expected)
so WA is to use any boud speed except 9600

**Comment by knee-koh** [comment]
Thanks for tracking this! For now I'll set the default baud rate to be something other than 9600. I'm not sure why there are timing issues on windows; Linux and Mac seem to handle serial baud a little bit better, though truthfully I have not seen this have an effect in my testing.
